### PR TITLE
(Feat) Added ok.ru and vk.com

### PR DESCRIPTION
**Pull request by cvaize**
Added Russian social networks 
https://ok.ru/
https://vk.com/

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Hi @cvaize, cool to see that you are using this module!

Could you move the regexes to their alphabetical place? (the list is now nicey ordered :P)
Could you also add these to the tests?

**Comment by cvaize** [comment]
Done. Thank you for your work!

**Comment by AdriVanHoudt** [comment]
@cvaize Thanks for the PR! 🚀

**Comment by AdriVanHoudt** [comment]
Published under 1.2.0 ✨

**Pull request merged**
